Search.appendIndex(
    [
                {
            "fqsen": "\\zozor\\Paginator",
            "name": "Paginator",
            "summary": "Main\u0020class",
            "url": "classes/zozor-Paginator.html"
        },                {
            "fqsen": "\\zozor\\Paginator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "class\u0027s\u0020constructor",
            "url": "classes/zozor-Paginator.html#method___construct"
        },                {
            "fqsen": "\\zozor\\Paginator\u003A\u003AnewPage\u0028\u0029",
            "name": "newPage",
            "summary": "create\u0020data\u0020for\u0020un\u0020new\u0020page",
            "url": "classes/zozor-Paginator.html#method_newPage"
        },                {
            "fqsen": "\\zozor\\Paginator\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "print\u0020json\u0020of\u0020pagination\u0027array\u0020by\u0020default",
            "url": "classes/zozor-Paginator.html#method___toString"
        },                {
            "fqsen": "\\zozor\\Paginator\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "get\u0020the\u0020pagination\u0027array",
            "url": "classes/zozor-Paginator.html#method_get"
        },                {
            "fqsen": "\\zozor\\Paginator\u003A\u003AgetJson\u0028\u0029",
            "name": "getJson",
            "summary": "get\u0020the\u0020array\u0020of\u0020pagination\u0020in\u0020json\u0020format",
            "url": "classes/zozor-Paginator.html#method_getJson"
        },                {
            "fqsen": "\\zozor\\Paginator\u003A\u003A\u0024total",
            "name": "total",
            "summary": "total\u0020number\u0020of\u0020records",
            "url": "classes/zozor-Paginator.html#property_total"
        },                {
            "fqsen": "\\zozor\\Paginator\u003A\u003A\u0024per_page",
            "name": "per_page",
            "summary": "per_page\u0020number\u0020of\u0020records\u0020per\u0020page",
            "url": "classes/zozor-Paginator.html#property_per_page"
        },                {
            "fqsen": "\\zozor\\Paginator\u003A\u003A\u0024current",
            "name": "current",
            "summary": "current\u0020current\u0020page\u0020number",
            "url": "classes/zozor-Paginator.html#property_current"
        },                {
            "fqsen": "\\zozor\\Paginator\u003A\u003A\u0024max_to_show",
            "name": "max_to_show",
            "summary": "max_to_show\u0020number\u0020of\u0020showed\u0020buttons",
            "url": "classes/zozor-Paginator.html#property_max_to_show"
        },                {
            "fqsen": "\\zozor\\Paginator\u003A\u003A\u0024nb_page",
            "name": "nb_page",
            "summary": "number\u0020of\u0020calculated\u0020pages",
            "url": "classes/zozor-Paginator.html#property_nb_page"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\zozor",
            "name": "zozor",
            "summary": "",
            "url": "namespaces/zozor.html"
        }            ]
);
